/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_AHB1ENR (*(volatile uint32_t*) 0x40023830)
#define GPIOA_MODER (*(volatile uint32_t*) 0x40020000)
#define GPIOA_ODR (*(volatile uint32_t*) 0x40020014)


int main(void)
{

	RCC_AHB1ENR |= (1 << 0);
	GPIOA_MODER &=  ~(3 << 10);
	GPIOA_MODER |= (1 << 10);

	for(;;) {

		GPIOA_ODR ^= (1 << 5);

		for (volatile uint32_t i = 0; i < 500000; i++) {
			continue;
		}
	}

}
